baseURL = 'https://www.thetechbiscuit.com'
languageCode = 'en-us'
title = 'TheTechBiscuit'
theme = "techbiscuits"
contentDir = "content"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[permalinks]
    blog = "/blog/:filename/"

[params]
    description = "Read TheTechBiscuit, authored by Zack Baxter."
    keywords = "TechBiscuit, blog, personal website"
    author = "Zack Baxter"
    og_image = "/images/social-card.png"